### ISSUE TITLE
permissions for fly and heal not working

### ISSUE THREAD

**Issue by OGTEnzoHD** [Thutmose/ThutPerms#2]
Hi i have set up permissions for my server using this mod and most permissions work but thut essentials perms and world edit permissions, below is my immortal rank they get a message saying "you do not have permission" when doing /fly and /heal.

http://pastebin.com/94dwhE5T

also giving permission node worldedit.* does not work on admin ranks

any help would be gratefully appreciated.

**Comment by Thutmose** [comment]
to use commands that inherently require OP, you either need to give OP to everyone in that group manually (they will still only be able to use the commands in their group) or you will need to set allCommandUse to true in the configs.  I would suggest being careful with allCommandUse, and making sure that none of your other mods do anything that checks it instead of normal command permissions, as if they do, it might allow players to do things they shouldn't be able to.

**Comment by OGTEnzoHD** [comment]
Is there a possible way that this could change, mainly because there are certain things that spam my console eg, kits that are a macro of the /give command that you see when only OP. Also if i set allCommandUse: true it will cause some difficulties due to mods checking for this. i appreciate that you are saying they inherently require OP but the permission node should bypass that rule not follow it.

thank you for the information though i will just be unable to use these commands for now.

**Comment by Thutmose** [comment]
I can see about making a way to configure the inherent permissions of the commands in Thut Essentials, which will fix your particular issue here, it will allow you to set /fly and /heal to not require OP, but it will only work for commands from Thut Essentials, it won't work for other mods, or vanilla commands.

I also do have plans for  a /kit command in Thut Essentials, I just have not got around to actually making it yet.

the problem with bypassing OP is that vanilla has it hardcoded in, which is what the allCommandUse removes.  Sponge/Bukkit completely overwrite vanilla everything with something very much like a core mod in forge, which results in them having massive compatiblity issues with mods, I don't want to cause that kind of issue with other mods, which is why this is the way I have dealt with OP use

The check for OP is done before any events are sent to mods, so I cannot check the permission before the server denies the command use, so I have to use the allCommandUse to allow not op players to access OP commands

**Comment by Thutmose** [comment]
The next version of Thut Essentials will have the following config option:
```
    S:commandPermissionLevels <
        heal:2
     >
```

you can add whatever command name that is actually from thutessentials to this, and it will assign that permission level to the command.  permission level of 0 will mean anyone can use the command, without needing op, or allCommandUse.  Note that this will only apply to thutessentials commands, as it will require ASM or other such bytecode manipulation to make it apply to commands not added by me.

**Comment by OGTEnzoHD** [comment]
that is perfect thank you so much i love the mod and we use it on all our servers thank you again

**Comment by Thutmose** [comment]
these changes have been uploaded to curse as 1.5.13/1.6.2 (depending on 1.10.2 or 1.11 minecraft)

**Comment by OGTEnzoHD** [comment]
can i ask what the numbers mean, like what number will make it so normal members dont have it but a group with the permission node will have it. and not need OP

**Comment by Thutmose** [comment]
oh, those are the vanilla permission levels, but modified such that 0 doesn't need op, anything from 0-2 can be used in a command sign (where you right click sign and it does command), and 3-4 requires the server console or a player.

0 or less lets any player or command block use the command.

**Comment by OGTEnzoHD** [comment]
right ok so setting to 0 will still make it so that a player has to have the permission node to work though

**Comment by Thutmose** [comment]
correct, thut permissions will then apply on top of that config, so if you set all of the thut essentials commands to 0, thut permissions will still apply, and only players with the permission can use the command.

**Comment by OGTEnzoHD** [comment]
thank you :D
