### ISSUE TITLE
ThutPerms overriding vanilla ops

### ISSUE THREAD

**Issue by xenoflot** [Thutmose/ThutPerms#3]
Hi,

I installed ThutPerms on my test server and I've found that despite being an operator (indeed the only operator and only user on this server!) I do not have access to commands that I should.
/gamemode, /time, /give and /toggledownfall are all refused.

If possible, I feel that a permission mod should not override permissions that are given by vanilla. If however that's just a fact of modded life, then I'll shut up and go RTFM to figure out how to make myself an op under ThutPerms :)

Cheers!

**Comment by Thutmose** [comment]
the blocking of vanilla OP is intentional, as it allows you to have differing levels of "op" by using the permission groups instead, you could make a group of players who can use /tp, but not /give

There are two ways to get yourself able to use all commands:

1. Put yourself in a group which has the "all" permission set, you can set "all" for a group with: '/editPerms [group] all true' from the server console, then can use /editGroup add [player] [group] to add [player] to the group.
2. specifically give your player all permissions via '/editPlayer [player] all true' which should specifically allow [player] to use all commands.

**Comment by xenoflot** [comment]
Got it. Thanks!
