### ISSUE TITLE
Users are not removed from mods group after being deopped

### ISSUE THREAD

**Issue by adkinss** [Thutmose/ThutPerms#31]
Users with OP are automatically added to the "mods" group that allows them to use additional commands.  However, users that have OP removed are not removed from the "mods" group, which means they can continue to use OP commands when they shouldn't be able too.

The code that deals with this is here:
https://github.com/Thutmose/ThutPerms/blob/1.12/src/main/java/thut/permissions/PermissionsManager.java#L182-L191

A couple suggestions on how to deal with this:

1.  Add code to the PlayerLoggin() function to check for members in the "mods" group and remove them if they no longer have OP.
2.  Not worry about it at all and just remove the code in PlayerLoggin() that checks for OP  and not add anybody to the "mods" group.  However, this forces admins to manage the "mods" group manually, which may not be ideal.
3. Override the /op and /deop commands to automatically add and remove users from the "mods" group.  Also change the PlayerLoggin() function to only check status for the player logging in and adjust the "mods" membership for that player accordingly.  This is the option I would prefer to see implemented.

Thank you!

**Comment by Thutmose** [comment]
I will fix this issue by doing the following:

I will remove the code that actually adds players to the initial and mods groups.
Instead, if they are not in any group, it will do the following:
If opped, will claim they are in the mods group when checked.
Otherwise, will claim they are in the initial group.

This will fix the issue, as now, unless you have specifically moved the player into a group (where you wouldn't want them randomly moving to mods anyway), then they will show in initial or mods, depending on OP state
